---
title: "APEP"
author: "Nikita Sleptcov"
date: "5/19/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Installing/loading necessary packages
```{r}
library(haven)
library(foreign)
library(lme4)
library(lmerTest)
library(effects)
library(emmeans)
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyverse)
```
Reading in data from Alberta Provincial Election Project and looking at data
```{r}
apep <- read_sav("apep.sav", user_na = F)
View(apep) #shows you your data
summary(apep) #gives you summary of your data
dim(apep) # tells the size of dataframe
head(apep) #shows headers of columns 
nrow(apep) # To get the number of rows
ncol(apep) # To get the number of columns
str(apep) # tells structure of the data
```
Recoding zipcodes omitting missing values
```{r}
apep$zipcode <- subset(apep$Q20, !is.na(apep$Q20))
str(apep$zipcode)
#remove white space 
apep$zipcode <- str_replace_all(apep$zipcode, fixed(" "), "") #remove all white spaces in Zip codes
apep$zipcode <- substr(apep$zipcode, start = 1, stop = 2) #selects 2 characters from a string and make it a differeте column
str(apep$zipcode)
# as.factor(apep$zipcode)
# as.character(apep$zipcode)
fct_count(apep$zipcode)
unique(apep$zipcode)

#this code doesn't do what I need.
levels(apep$zipcode) <- list(Calgary=c("T1", "T2", "T3"), Edmonton=c("T5","T6"))
apep$zipcode
apep$cities <- fct_collapse(apep$zipcode,
  Calgary = c("T1", "T2", "T3"),
  Edmonton = c("T5", "T6"),
  Grande_Prairie="T8",
  Red_Dear="T4",
  Other=c())
fct_count(apep$cities)

save(apep, file = "APEP 2019")
```

